import Link from "next/link";
import { Archive, CheckCircle2, Coins, ExternalLink, KeyRound, LockKeyhole, PlusCircle, RotateCcw, School, Settings2, Users } from "lucide-react";
import { createClassroom, setClassroomActive, updateClassroom } from "@/actions";
import { db } from "@/lib/db";
import { lockManagement } from "@/lib/auth";

export const dynamic = "force-dynamic";

export default async function Classrooms({ searchParams }: { searchParams: Promise<{ updated?: string; archived?: string; restored?: string }> }) {
  const [query, classrooms] = await Promise.all([
    searchParams,
    db.classroom.findMany({ orderBy: [{ active: "desc" }, { name: "asc" }], include: { teachers: { orderBy: { createdAt: "asc" }, take: 1 }, _count: { select: { pupils: true } } } }),
  ]);
  const active = classrooms.filter(c => c.active);
  const archived = classrooms.filter(c => !c.active);
  const pupilCount = active.reduce((sum, c) => sum + c._count.pupils, 0);
  return <main className="school-admin">
    <header className="school-admin-header"><div className="manager-logo"><Coins/></div><div><span className="eyebrow">School administration</span><h1>Brunner Bucks classrooms</h1><p>Set up and maintain each classroom’s private bookmark, teacher access and school-year details.</p></div><form action={lockManagement} className="management-lock"><button className="btn light"><LockKeyhole size={16}/> Lock management</button></form></header>
    {(query.updated||query.archived||query.restored)&&<div className="manager-success"><CheckCircle2/> Classroom changes saved successfully.</div>}
    <section className="manager-stats"><article className="card"><School/><span><b>{active.length}</b><small>Active classrooms</small></span></article><article className="card"><Users/><span><b>{pupilCount}</b><small>Pupils across school</small></span></article><article className="card"><Archive/><span><b>{archived.length}</b><small>Archived classrooms</small></span></article></section>
    <div className="school-admin-grid"><section className="managed-classrooms"><div className="section-title"><Settings2/><div><h2>Manage classrooms</h2><p className="muted">Edit details, replace a teacher password or copy the class link for bookmarks.</p></div></div><div className="managed-class-list">{active.map(c=>{const teacher=c.teachers[0];return <article className="card managed-class-card" key={c.id}><div className="managed-class-head"><span className="classroom-icon"><School/></span><div><h2>{c.name}</h2><p>{teacher?.displayName||"Teacher"} · {c.schoolYear} · {c._count.pupils} pupils</p></div><Link className="btn gold" href={`/class/${c.slug}`}>Open class <ExternalLink size={16}/></Link></div><div className="class-bookmark"><span>Bookmark link</span><code>/class/{c.slug}</code></div><form action={updateClassroom} className="class-edit-form"><input type="hidden" name="id" value={c.id}/><label>Classroom name<input className="input" name="name" defaultValue={c.name} required/></label><label>School year<input className="input" name="schoolYear" defaultValue={c.schoolYear} required/></label><label>Teacher name<input className="input" name="teacherName" defaultValue={teacher?.displayName||"Teacher"} required/></label><label><span>Replace password <small>Optional</small></span><div className="password-field"><KeyRound/><input className="input" name="password" type="password" minLength={8} placeholder="Leave blank to keep current"/></div></label><div className="class-form-actions"><button className="btn light">Save classroom details</button><button className="btn danger" formAction={setClassroomActive} name="active" value="false"><Archive size={16}/> Archive classroom</button></div></form></article>})}</div>{archived.length>0&&<section className="archived-section"><h2>Archived classrooms</h2><p className="muted">Archived links and logins are unavailable, but all classroom data is preserved.</p>{archived.map(c=><article className="card archived-class" key={c.id}><span><b>{c.name}</b><small>{c.schoolYear} · {c._count.pupils} pupils</small></span><form action={setClassroomActive}><input type="hidden" name="id" value={c.id}/><button className="btn light" name="active" value="true"><RotateCcw size={16}/> Restore</button></form></article>)}</section>}</section>
      <aside><form action={createClassroom} className="card create-classroom-card"><span className="form-icon"><PlusCircle/></span><span className="eyebrow">New classroom</span><h2>Create a classroom space</h2><p className="muted">A fresh wallet system, reward shop, reports, avatars and bookmark link will be created automatically.</p><label>Classroom name<input className="input" name="name" placeholder="e.g. Oak Class" required/></label><label>School year<input className="input" name="schoolYear" placeholder="e.g. 2026–27" required/></label><label>Teacher name<input className="input" name="teacherName" placeholder="e.g. Ms. Hennessy" required/></label><label>Initial teacher password<input className="input" name="password" type="password" minLength={8} placeholder="At least 8 characters" required/></label><button className="btn gold full-button">Create classroom and link</button></form><div className="admin-note"><b>School-only area</b><p>This page is for classroom administration. Pupil and teacher devices should bookmark their individual class link instead.</p></div></aside>
    </div>
  </main>;
}
